import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Suspense } from "react";
import "./globals.css";
import { RootLoading } from "./root-loading";
import { ThemeColorSync } from "@/components/ThemeColorSync";
import { THEME_COLORS } from "@/lib/theme";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/**
 * Canonical origin used for absolute metadata URLs (icons, manifest).
 *
 * The admin panel is deployed separately from the public site, so it uses its
 * own `NEXT_PUBLIC_ADMIN_SITE_URL` when present; `NEXT_PUBLIC_SITE_URL` and the
 * deployment URL are accepted as fallbacks. When nothing is configured the
 * icons stay relative (still correct — only absolute-only metadata such as
 * og:image would need an origin).
 */
const adminSiteUrl =
  process.env.NEXT_PUBLIC_ADMIN_SITE_URL ??
  process.env.NEXT_PUBLIC_SITE_URL ??
  (process.env.VERCEL_URL ? `https://${process.env.VERCEL_URL}` : null);

export const metadata: Metadata = {
  ...(adminSiteUrl ? { metadataBase: new URL(adminSiteUrl) } : {}),
  applicationName: "Couples Corner Admin",
  title: {
    default: "Couples Corner Admin",
    template: "%s | Couples Corner Admin",
  },
  description:
    "Couples Corner — platform administration dashboard.",
  // PWA manifest (app/manifest.ts) — same navy theme + brand icons as the app.
  manifest: "/manifest.webmanifest",
  // iOS: standalone web app with a navy status bar to match the splash.
  appleWebApp: {
    capable: true,
    title: "Couples Corner Admin",
    statusBarStyle: "black-translucent",
  },
  // Brand icon set generated by web/scripts/generate-brand-icons.cjs
  // (App Router file conventions serve /favicon.ico, /icon.png, /apple-icon.png).
  icons: {
    icon: [
      { url: "/favicon.ico", sizes: "any" },
      { url: "/icon.png", type: "image/png", sizes: "512x512" },
      { url: "/icons/icon-192.png", type: "image/png", sizes: "192x192" },
    ],
    shortcut: [{ url: "/favicon.ico" }],
    apple: [{ url: "/apple-icon.png", type: "image/png", sizes: "180x180" }],
  },
};

export const viewport: Viewport = {
  // Brand navy from the shared THEME_COLORS constant (mirrors the `--background`
  // CSS token) — keeps mobile browser chrome and the installed-app splash in
  // step with the dark admin surface (see `.admin-dark` / `.app-canvas`).
  themeColor: THEME_COLORS.themeColor,
  colorScheme: "dark",
};


export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-background text-foreground">
        <ThemeColorSync />
        <Suspense fallback={<RootLoading />}>{children}</Suspense>
      </body>
    </html>
  );
}
